# render.yaml
services:
  - type: web
    name: email-categorization-system
    runtime: image
    repo: https://github.com/HarshS1120/email-categorization-system
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"